wandb_version: 1

batch_size:
  desc: null
  value: 32
dropout_p:
  desc: null
  value: 0.5
epochs:
  desc: null
  value: 150
hidden_layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.003875
optimizer:
  desc: null
  value: adam
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.39.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712045367.637429
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.11
      5: 0.16.2
      6: 4.39.1
      8:
      - 3
      - 5
      13: windows-amd64
