wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.39.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711540804.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.11.7
      5: 0.16.4
      6: 4.39.0
      8:
      - 3
      - 5
      13: windows-amd64
batch_size:
  desc: null
  value: 64
dropout_p:
  desc: null
  value: 0
epochs:
  desc: null
  value: 50
hidden_layers:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.0027500000000000003
optimizer:
  desc: null
  value: adam
